# Preface {.unnumbered}

Python workshop taught by Professor Markus Loecher (HWR Berlin). The workshop will run in-person June 6 - 9 in room VC 14-280 (from 10am to 1pm and 2 to 5pm). 

## About this python workshop


Goals
-----

This 4 day workshop is intended to introduce participants
to the python language. It is designed to provide the solid
foundation needed to conduct data analysis and visualization for data
science. While no previous experience is required, some basic
programming or data science experience is helpful.

I will lean heavily on the book [Python for Data Analysis](https://wesmckinney.com/book/) (as well as the [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)).

The first day will focus on the fundamentals of data types and flow structures while the ultimate goal of the course will be to introduce you to _statistical thinking, data literacy and modeling_.


DataCamp
------
[DataCamp](https://app.datacamp.com/) is a pretty good resource for students to learn coding and data analysis skills.
By completing the DataCamp courses listed below we would be able to significantly shorten 
the time we spend on basics and open up more space for data science concepts.

* [Introduction to Python](https://app.datacamp.com/learn/courses/intro-to-python-for-data-science)
* [Intermediate Python](https://app.datacamp.com/learn/courses/intermediate-python)

If you have extra time:
* [Data Manipulation with pandas](https://app.datacamp.com/learn/courses/data-manipulation-with-pandas)

And much more advanced and totally optional:

* [Python Data Science Toolbox (Part 1)](https://www.datacamp.com/courses/python-data-science-toolbox-part-1)
* [Python Data Science Toolbox (Part 2)](https://www.datacamp.com/courses/python-data-science-toolbox-part-2)
* [Statistical Thinking in Python (Part 1)](https://www.datacamp.com/courses/statistical-thinking-in-python-part-1)
* [Statistical Thinking in Python (Part 2)](https://www.datacamp.com/courses/statistical-thinking-in-python-part-2)

Coding Environment
------
The most convenient environment for you to code in might be [Google Colab](https://colab.research.google.com/), for which you probably need a gmail account. It does not hurt to look at the 2-minute intro video.
If you prefer a real IDE, I would recommend [Visual Studio](https://visualstudio.microsoft.com/downloads/) or [PyCharm](https://www.jetbrains.com/pycharm/download/). (I will not be able to help much with the latter though)

Agenda
------

### Day 1: Basic python programming

-   basic data types: lists, tuples, dictionaries, strings
-   control structures (for, if else, while)
-   functions
-   numpy arrays: slicing and subsetting, axis
-   Probabilistic Simulations
-   basic plots

### Day 2: pandas and visualization

-   pandas Data Frames: slicing and subsetting
-   Counting and Summary Statistics
-   Handling Files
-   Grouped Operations
-   plotting with pandas
-   Contingency Tables as models

### Day 3: Statistical Modeling

-   A/B Testing and sampling distributions
-   Hypothesis Testing
    * parametric
    * permutation
    * the bootstrap
-   regression
    * simple and multiple
    * logistic
    * categorical variables and interactions
    * regularization

### Day 4: Machine Learning

-   Basic ML tools
    * Cross Validation
    * sklearn
    * Data Cleaning
-   Classification and Regression Trees
-   Random Forests and Boosting
-   Exlainable ML
    * Partial dependence plots
    * SHAP values

### If time permits

- Word embeddings such as word2vec  
- Sentiment analysis
- Internet scraping
- Topic models

Lecturer
=====


[Prof. Dr. Markus
Loecher](http://www.hwr-berlin.de/fachbereich-wirtschaftswissenschaften/kontakt/personen/kontakt-info/2184/ "ML official university link")

Professor for Mathematics and Statistics

[Berlin School of Economics and Law](http://www.hwr-berlin.de "BSEL Homepage")

[linkedin](https://www.linkedin.com/in/loecher/)

[researchgate](https://www.researchgate.net/profile/Markus-Loecher)

[my blog](https://markusloecher.github.io/ "blog")


